spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 1
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 3200
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    ttl:
      global: 60s
      config:
#        cache:
#          user: 30s
#          org: 30s
        override: true
